export { default as Home } from './Sections/Home/Home'
export { default as Articles } from './Sections/Articles/Articles'
export { default as Gallery } from './Sections/Gallery/Gallery'
export { default as Features } from './Sections/Features/Features'
export { default as Testimonials } from './Sections/Testimonials/Testimonials'
export { default as TeamMembers } from './Sections/TeamMembers/TeamMembers'
export { default as Services } from './Sections/Services/Services'
export { default as OurSkills } from './Sections/OurSkills/OurSkills'
export { default as Works } from './Sections/Works/Works'
export { default as LatestEvents } from './Sections/LatestEvents/LatestEvents'
export { default as PricingPlans } from './Sections/PricingPlans/PricingPlans'
export { default as TopVideos } from './Sections/TopVideos/TopVideos'
export { default as Stats } from './Sections/Stats/Stats'
export { default as Discount } from './Sections/Discount/Discount'

