export { default as MT } from './MainTitle/MainTitle'
export { default as SC } from './SectionContainer/SectionContainer'
export { default as ND } from './NormalDiv/NormalDiv'
export { default as MS } from './MainSection/MainSection'
export { default as IMG } from './img/img'